name: CI

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        env:
          SHELLCHECK_OPTS: "-e SC2086,SC2016,SC2015"
        run: shellcheck $(find . -name "*.sh") 
      - name: tests
        run: ./tests/run-tests.sh
